const content=[
    {
        _id:1,
        name:"Shang Chi and the legend of ten rings",
        imgsrc:"../images/m1.jpg",
        rating:7,
        category:"Movie",
        genre:"action",
        duration:'90min',
        release:"2021",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis tempora quidem earum a quibusdam laborum enim consequatur quae dolores, perspiciatis cupiditate dolorem reprehenderit pariatur ullam illo cumque. Tempore, at mollitia odit esse blanditiis reprehenderit magnam tenetur culpa ut, eveniet incidunt voluptas molestiae velit laborum ad explicabo suscipit quo vel, animi aut iusto non ipsum labore? Dolorum officia voluptatum cupiditate ut!",
        director:"lorem",
        cast:"ennie, minnie , mynie , mo"

    },
    {
        _id:2,
        name:"Black Panther",
        imgsrc:"../images/blackpanther.jpg",
        rating:9,
        category:"Movie",
        genre:"sci fi",
        duration:'140min',
        release:"2016",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis tempora quidem earum a quibusdam laborum enim consequatur quae dolores, perspiciatis cupiditate dolorem reprehenderit pariatur ullam illo cumque. Tempore, at mollitia odit esse blanditiis reprehenderit magnam tenetur culpa ut, eveniet incidunt voluptas molestiae velit laborum ad explicabo suscipit quo vel, animi aut iusto non ipsum labore? Dolorum officia voluptatum cupiditate ut!",
        director:"lorem",
        cast:"ennie, minnie , mynie , mo"

    },
    {   _id:3,
            name:"Dumb and Dumber",
        imgsrc:"../images/dumbanddumber.jpg",
        rating:9.3,
        category:"Movie",
        genre:"comedy",
        duration:'90min',
        release:"2013",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis tempora quidem earum a quibusdam laborum enim consequatur quae dolores, perspiciatis cupiditate dolorem reprehenderit pariatur ullam illo cumque. Tempore, at mollitia odit esse blanditiis reprehenderit magnam tenetur culpa ut, eveniet incidunt voluptas molestiae velit laborum ad explicabo suscipit quo vel, animi aut iusto non ipsum labore? Dolorum officia voluptatum cupiditate ut!",
        director:"lorem",
        cast:"ennie, minnie , mynie , mo"

    },
    { _id:4,
        name:"Free Guy",
        imgsrc:"../images/freeguy.jpg",
        rating:7,
        category:"Movie",
        genre:"sci fi",
        duration:'120min',
        release:"2021",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis tempora quidem earum a quibusdam laborum enim consequatur quae dolores, perspiciatis cupiditate dolorem reprehenderit pariatur ullam illo cumque. Tempore, at mollitia odit esse blanditiis reprehenderit magnam tenetur culpa ut, eveniet incidunt voluptas molestiae velit laborum ad explicabo suscipit quo vel, animi aut iusto non ipsum labore? Dolorum officia voluptatum cupiditate ut!",
        director:"lorem",
        cast:"ennie, minnie , mynie , mo"

    },
    { _id:5,
        name:"Hangover",
        imgsrc:"../images/hangover.jpg",
        rating:6,
        category:"Movie",
        genre:"comedy",
        duration:'130min',
        release:"2015",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis tempora quidem earum a quibusdam laborum enim consequatur quae dolores, perspiciatis cupiditate dolorem reprehenderit pariatur ullam illo cumque. Tempore, at mollitia odit esse blanditiis reprehenderit magnam tenetur culpa ut, eveniet incidunt voluptas molestiae velit laborum ad explicabo suscipit quo vel, animi aut iusto non ipsum labore? Dolorum officia voluptatum cupiditate ut!",
        director:"lorem",
        cast:"ennie, minnie , mynie , mo"

    },
    { _id:6,
        name:"Lights Out",
        imgsrc:"../images/lightsout.jpg",
        rating:4,
        category:"Movie",
        genre:"horror",
        duration:'110min',
        release:"2017",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis tempora quidem earum a quibusdam laborum enim consequatur quae dolores, perspiciatis cupiditate dolorem reprehenderit pariatur ullam illo cumque. Tempore, at mollitia odit esse blanditiis reprehenderit magnam tenetur culpa ut, eveniet incidunt voluptas molestiae velit laborum ad explicabo suscipit quo vel, animi aut iusto non ipsum labore? Dolorum officia voluptatum cupiditate ut!",
        director:"lorem",
        cast:"ennie, minnie , mynie , mo"

    },
    {  _id:7,
        name:"Mr Right",
        imgsrc:"../images/mrright.jpg",
        rating:6,
        category:"Movie",
        genre:"comedy",
        duration:'90min',
        release:"2011",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis tempora quidem earum a quibusdam laborum enim consequatur quae dolores, perspiciatis cupiditate dolorem reprehenderit pariatur ullam illo cumque. Tempore, at mollitia odit esse blanditiis reprehenderit magnam tenetur culpa ut, eveniet incidunt voluptas molestiae velit laborum ad explicabo suscipit quo vel, animi aut iusto non ipsum labore? Dolorum officia voluptatum cupiditate ut!",
        director:"lorem",
        cast:"ennie, minnie , mynie , mo"

    },
    {   _id:8,
        name:"Rick and Morty",
        imgsrc:"../images/rickandmorty.jpg",
        rating:9,
        category:"Show",
        genre:"sci fi",
        duration:'20min',
        release:"2017",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis tempora quidem earum a quibusdam laborum enim consequatur quae dolores, perspiciatis cupiditate dolorem reprehenderit pariatur ullam illo cumque. Tempore, at mollitia odit esse blanditiis reprehenderit magnam tenetur culpa ut, eveniet incidunt voluptas molestiae velit laborum ad explicabo suscipit quo vel, animi aut iusto non ipsum labore? Dolorum officia voluptatum cupiditate ut!",
        director:"lorem",
        cast:"ennie, minnie , mynie , mo"

    },
    {  _id:9,
        name:"Sinister",
        imgsrc:"../images/sinister.jpeg",
        rating:5,
        category:"Movie",
        genre:"horror",
        duration:'140min',
        release:"2016",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis tempora quidem earum a quibusdam laborum enim consequatur quae dolores, perspiciatis cupiditate dolorem reprehenderit pariatur ullam illo cumque. Tempore, at mollitia odit esse blanditiis reprehenderit magnam tenetur culpa ut, eveniet incidunt voluptas molestiae velit laborum ad explicabo suscipit quo vel, animi aut iusto non ipsum labore? Dolorum officia voluptatum cupiditate ut!",
        director:"lorem",
        cast:"ennie, minnie , mynie , mo"

    },
    {   _id:10,
        name:"Strangers Thing",
        imgsrc:"../images/strangersthing.jpg",
        rating:8,
        category:"Movie",
        genre:"horror",
        duration:'40min',
        release:"2018",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis tempora quidem earum a quibusdam laborum enim consequatur quae dolores, perspiciatis cupiditate dolorem reprehenderit pariatur ullam illo cumque. Tempore, at mollitia odit esse blanditiis reprehenderit magnam tenetur culpa ut, eveniet incidunt voluptas molestiae velit laborum ad explicabo suscipit quo vel, animi aut iusto non ipsum labore? Dolorum officia voluptatum cupiditate ut!",
        director:"lorem",
        cast:"ennie, minnie , mynie , mo"

    },
    {   _id:11,
        name:"The johnsons",
        imgsrc:"../images/thejohnsons.jpg",
        rating:7,
        category:"Movie",
        genre:"comedy",
        duration:'90min',
        release:"2017",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis tempora quidem earum a quibusdam laborum enim consequatur quae dolores, perspiciatis cupiditate dolorem reprehenderit pariatur ullam illo cumque. Tempore, at mollitia odit esse blanditiis reprehenderit magnam tenetur culpa ut, eveniet incidunt voluptas molestiae velit laborum ad explicabo suscipit quo vel, animi aut iusto non ipsum labore? Dolorum officia voluptatum cupiditate ut!",
        director:"lorem",
        cast:"ennie, minnie , mynie , mo"

    },
    {  _id:12,
        name:"The Neighbourhood",
        imgsrc:"../images/theneightbourhood.jpg",
        rating:9,
        category:"Show",
        genre:"comedy",
        duration:'20min',
        release:"2017",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis tempora quidem earum a quibusdam laborum enim consequatur quae dolores, perspiciatis cupiditate dolorem reprehenderit pariatur ullam illo cumque. Tempore, at mollitia odit esse blanditiis reprehenderit magnam tenetur culpa ut, eveniet incidunt voluptas molestiae velit laborum ad explicabo suscipit quo vel, animi aut iusto non ipsum labore? Dolorum officia voluptatum cupiditate ut!",
        director:"lorem",
        cast:"ennie, minnie , mynie , mo"

    },
    {   _id:13,
        name:"The Orville",
        imgsrc:"../images/theorville.jpg",
        rating:8,
        category:"Show",
        genre:"sci fi",
        duration:'30min',
        release:"2016",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis tempora quidem earum a quibusdam laborum enim consequatur quae dolores, perspiciatis cupiditate dolorem reprehenderit pariatur ullam illo cumque. Tempore, at mollitia odit esse blanditiis reprehenderit magnam tenetur culpa ut, eveniet incidunt voluptas molestiae velit laborum ad explicabo suscipit quo vel, animi aut iusto non ipsum labore? Dolorum officia voluptatum cupiditate ut!",
        director:"lorem",
        cast:"ennie, minnie , mynie , mo"

    },
    {   _id:14,
        name:"Loki",
        imgsrc:"../images/loki.jpg",
        rating:8,
        category:"Show",
        genre:"adventure",
        duration:'45min',
        release:"2021",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis tempora quidem earum a quibusdam laborum enim consequatur quae dolores, perspiciatis cupiditate dolorem reprehenderit pariatur ullam illo cumque. Tempore, at mollitia odit esse blanditiis reprehenderit magnam tenetur culpa ut, eveniet incidunt voluptas molestiae velit laborum ad explicabo suscipit quo vel, animi aut iusto non ipsum labore? Dolorum officia voluptatum cupiditate ut!",
        director:"lorem",
        cast:"ennie, minnie , mynie , mo"

    },
    {   _id:15,
        name:"Wanda vision",
        imgsrc:"../images/wandavision.jpeg",
        rating:7,
        category:"Show",
        genre:"drama",
        duration:'40min',
        release:"2021",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis tempora quidem earum a quibusdam laborum enim consequatur quae dolores, perspiciatis cupiditate dolorem reprehenderit pariatur ullam illo cumque. Tempore, at mollitia odit esse blanditiis reprehenderit magnam tenetur culpa ut, eveniet incidunt voluptas molestiae velit laborum ad explicabo suscipit quo vel, animi aut iusto non ipsum labore? Dolorum officia voluptatum cupiditate ut!",
        director:"lorem",
        cast:"ennie, minnie , mynie , mo"

    },
    {  _id:16,
        name:"Falcon and the Winter Soldier",
        imgsrc:"../images/falconandwinter.jpg",
        rating:6,
        category:"Show",
        genre:"action",
        duration:'50min',
        release:"2021",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis tempora quidem earum a quibusdam laborum enim consequatur quae dolores, perspiciatis cupiditate dolorem reprehenderit pariatur ullam illo cumque. Tempore, at mollitia odit esse blanditiis reprehenderit magnam tenetur culpa ut, eveniet incidunt voluptas molestiae velit laborum ad explicabo suscipit quo vel, animi aut iusto non ipsum labore? Dolorum officia voluptatum cupiditate ut!",
        director:"lorem",
        cast:"ennie, minnie , mynie , mo"

    },
    {  _id:17,
        name:"This is the end",
        imgsrc:"../images/thisistheend.jpg",
        rating:7,
        category:"Movie",
        genre:"comedy",
        duration:'90min',
        release:"2016",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis tempora quidem earum a quibusdam laborum enim consequatur quae dolores, perspiciatis cupiditate dolorem reprehenderit pariatur ullam illo cumque. Tempore, at mollitia odit esse blanditiis reprehenderit magnam tenetur culpa ut, eveniet incidunt voluptas molestiae velit laborum ad explicabo suscipit quo vel, animi aut iusto non ipsum labore? Dolorum officia voluptatum cupiditate ut!",
        director:"lorem",
        cast:"ennie, minnie , mynie , mo"

    },
    {   _id:18,
        name:"Tomorrow War",
        imgsrc:"../images/tommorowar.jpg",
        rating:8,
        category:"Movie",
        genre:"sci fi",
        duration:'90min',
        release:"2021",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis tempora quidem earum a quibusdam laborum enim consequatur quae dolores, perspiciatis cupiditate dolorem reprehenderit pariatur ullam illo cumque. Tempore, at mollitia odit esse blanditiis reprehenderit magnam tenetur culpa ut, eveniet incidunt voluptas molestiae velit laborum ad explicabo suscipit quo vel, animi aut iusto non ipsum labore? Dolorum officia voluptatum cupiditate ut!",
        director:"lorem",
        cast:"ennie, minnie , mynie , mo"

    },
    {   _id:19,
        name:"Us",
        imgsrc:"../images/us.jpeg",
        rating:6.3,
        category:"Movie",
        genre:"horror",
        duration:'120min',
        release:"2020",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis tempora quidem earum a quibusdam laborum enim consequatur quae dolores, perspiciatis cupiditate dolorem reprehenderit pariatur ullam illo cumque. Tempore, at mollitia odit esse blanditiis reprehenderit magnam tenetur culpa ut, eveniet incidunt voluptas molestiae velit laborum ad explicabo suscipit quo vel, animi aut iusto non ipsum labore? Dolorum officia voluptatum cupiditate ut!",
        director:"lorem",
        cast:"ennie, minnie , mynie , mo"

    },
    {  _id:20,
        name:"Wrecked",
        imgsrc:"../images/wrecked.jpg",
        rating:8,
        category:"Show",
        genre:"comedy",
        duration:'20min',
        release:"2019",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis tempora quidem earum a quibusdam laborum enim consequatur quae dolores, perspiciatis cupiditate dolorem reprehenderit pariatur ullam illo cumque. Tempore, at mollitia odit esse blanditiis reprehenderit magnam tenetur culpa ut, eveniet incidunt voluptas molestiae velit laborum ad explicabo suscipit quo vel, animi aut iusto non ipsum labore? Dolorum officia voluptatum cupiditate ut!",
        director:"lorem",
        cast:"ennie, minnie , mynie , mo"

    },
    {  _id:21,
        name:"X Men",
        imgsrc:"../images/xmen.jpg",
        rating:6.7,
        category:"Movie",
        genre:"sci fi",
        duration:'190min',
        release:"2018",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis tempora quidem earum a quibusdam laborum enim consequatur quae dolores, perspiciatis cupiditate dolorem reprehenderit pariatur ullam illo cumque. Tempore, at mollitia odit esse blanditiis reprehenderit magnam tenetur culpa ut, eveniet incidunt voluptas molestiae velit laborum ad explicabo suscipit quo vel, animi aut iusto non ipsum labore? Dolorum officia voluptatum cupiditate ut!",
        director:"lorem",
        cast:"ennie, minnie , mynie , mo"

    }
]


module.exports = content;